name: GitLab CI/CD

on:
  - push
  - delete

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: keninkujovic/gitlab-sync@2.0.0
      with:
        gitlab_url: https://gitlab.com/Lele971/CarMaintenance.git
        username: Lele971
        gitlab_pat: glpat-XoFwHtobYsTABa_NCzAT
