name: GitLab CI/CD

on:
  push:
  delete:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: keninkujovic/gitlab-sync@2.0.0
        with:
          gitlab_url: ${GIT_LAB_URI}           
          username:  ${GIT_LAB_USERNAME} 
          gitlab_pat: ${GIT_LAB_TOKEN}
